image: rust:1.64.0

stages:
- build
- test

contract_interstake_yield_generator:
  stage: test
  needs: []
  script:
  - cd contracts/interstake-yield-generator
  - rustc --version; cargo --version; rustup --version
  - RUST_BACKTRACE=1 cargo test --locked
  - cargo schema --locked

package_utils:
  stage: test
  needs: []
  script:
  - cd packages/utils
  - rustc --version; cargo --version; rustup --version; rustup target list --installed
  - cargo build --locked
  - cargo test --locked\

coverage:
  stage: test
  needs: []
  script:
  - rustup override set nightly
  - cargo install cargo-tarpaulin
  - cargo tarpaulin -v --all-features --force-clean --offline

lint:
  stage: build
  script:
  - rustc --version; cargo --version; rustup --version; rustup target list --installed
  - rustup component add rustfmt
  - rustup component add clippy
  - cargo clippy --tests -- -D warnings
  - cargo fmt -- --check

wasm_build:
  stage: build
  script:
  - rustc --version; cargo --version; rustup --version; rustup target list --installed
  - rustup target add wasm32-unknown-unknown
  - |
    for C in ./contracts/*/
    do
      echo "Compiling $(basename $C) ..."
      (cd $C && cargo build --release --lib --target wasm32-unknown-unknown --locked)
    done
  - cargo install --debug --version 1.1.2 cosmwasm-check
  - cosmwasm-check ./target/wasm32-unknown-unknown/release/*.wasm
